services:
  db:
    image: postgis/postgis:17-3.4
    container_name: data-alchemists-postgis-copy-ver
    restart: unless-stopped
    env_file: .env
    ports:
      - "5434:5432"                # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/db

volumes:
  pgdata: